In [1]:
import pandas as pd
import streamlit as st

In [20]:
selections = {'Steph S':['France','Colombia','Australia','Canada','South Africa','Saudi Arabia'],
              'Nick P':['Spain','Germany','Japan','Norway','Czechia','Ghana'],
              'Ian C':['France','Belgium','Switzerland','Canada','Czechia','Bosnia-Herzegovina'],
              'Yasmin S':['Argentina','Germany','Japan','Norway','Scotland','Ghana'],
              'Gavin F':['Argentina','Belgium','Ecuador','Canada','Scotland','Ghana'],
              'Matt C':['France','Germany','Turkey','Norway','Czechia','Bosnia-Herzegovina'],
              'Tim C':['France','Germany','Japan','Norway','Czechia','Bosnia-Herzegovina'],
              'Geoff T':['France','Germany','Switzerland','Norway','Scotland','Saudi Arabia'],
              'Caity H':['France','Mexico','Australia','Ivory Coast','South Africa','Ghana'],
              'Laura B':['Spain','Belgium','Switzerland','Norway','Scotland','Ghana'],
              'Jessie DB':['France','Germany','Iran','Norway','Tunisia','Curaçao'],
              'AJ B':['Spain','Mexico','Switzerland','Canada','Czechia','Bosnia-Herzegovina'],
              'Anita VR':['Brazil','Croatia','Ecuador','Ivory Coast','South Africa','Bosnia-Herzegovina']}
selections = pd.DataFrame(selections).T
selections = selections.reset_index().rename(columns={'index':'Person'}).melt(id_vars='Person',var_name='pot',value_name='Country')
selections.pot += 1
selections = selections.merge(selections.groupby('Country').Person.count().reset_index().rename(columns={'Person':'Count'}))
selections['Uniqueness'] = 1 - (selections['Count'] - 1) / (selections.Person.nunique() - 1)

In [21]:
groups = {'A':['MEX','RSA','KOR','CZE'],
          'B':['CAN','BIH','QAT','SUI'],
          'C':['BRA','MAR','HAI','SCO'],
          'D':['USA','PAR','AUS','TUR'],
          'E':['GER','CUW','CIV','ECU'],
          'F':['NED','JPN','SWE','TUN'],
          'G':['BEL','EGY','IRN','NZL'],
          'H':['ESP','CPV','KSA','URU'],
          'I':['FRA','SEN','IRQ','NOR'],
          'J':['ARG','ALG','AUT','JOR'],
          'K':['POR','COD','UZB','COL'],
          'L':['ENG','CRO','GHA','PAN']}

names = {'MEX':'Mexico','RSA':'South Africa','KOR':'South Korea','CZE':'Czechia',
         'CAN':'Canada','BIH':'Bosnia-Herzegovina','QAT':'Qatar','SUI':'Switzerland',
         'BRA':'Brazil','MAR':'Morocco','HAI':'Haiti','SCO':'Scotland',
         'USA':'United States','PAR':'Paraguay','AUS':'Australia','TUR':'Turkey',
         'GER':'Germany','CUW':'Curaçao','CIV':'Ivory Coast','ECU':'Ecuador',
         'NED':'Netherlands','JPN':'Japan','SWE':'Sweden','TUN':'Tunisia',
         'BEL':'Belgium','EGY':'Egypt','IRN':'Iran','NZL':'New Zealand',
         'ESP':'Spain','CPV':'Cape Verde Islands','KSA':'Saudi Arabia','URU':'Uruguay',
         'FRA':'France','SEN':'Senegal','IRQ':'Iraq','NOR':'Norway',
         'ARG':'Argentina','ALG':'Algeria','AUT':'Austria','JOR':'Jordan',
         'POR':'Portugal','COD':'Congo DR','UZB':'Uzbekistan','COL':'Colombia',
         'ENG':'England','CRO':'Croatia','GHA':'Ghana','PAN':'Panama'}

groups = pd.DataFrame(groups).T.reset_index().rename(columns={'index':'Group'}).melt(id_vars='Group',value_name='Short').drop(columns='variable')
groups['Country'] = groups.Short.replace(names)

In [40]:
import requests

API_KEY = "1d042d223fa447cf863e6e820aa3d96a"

r = requests.get(
    "https://api.football-data.org/v4/competitions/WC/matches",
    headers={"X-Auth-Token": API_KEY})

matches = []
for i in range(0,len(r.json()['matches'])):
    temp = r.json()['matches'][i]
    date = temp['utcDate']
    stage = temp['stage']
    home_team = temp['homeTeam']['name']
    away_team = temp['awayTeam']['name']
    home_score = temp['score']['fullTime']['home']
    away_score = temp['score']['fullTime']['away']
    matches.append([date,stage,home_team,away_team,home_score,away_score])
matches = pd.DataFrame(matches,columns=['Date','Stage','Home','Away','Home_Score','Away_Score'])
matches.Home = matches.Home.replace({v: k for k, v in names.items()})
matches.Away = matches.Away.replace({v: k for k, v in names.items()})
matches['key'] = matches.dropna(subset=['Home']).apply(lambda r: tuple(sorted([r['Home'], r['Away']])),axis=1)#
matches['unsort_key'] = matches.dropna(subset=['Home']).apply(lambda r: tuple(([r['Home'], r['Away']])),axis=1)#
mask = matches.key != matches.unsort_key
matches.loc[mask, ['Home_Score', 'Away_Score']] = (matches.loc[mask, ['Away_Score', 'Home_Score']].values)
matches['Home_Win'] = (matches.Home_Score > matches.Away_Score).astype('int')
matches['Away_Win'] = (matches.Home_Score < matches.Away_Score).astype('int')
matches['Draw'] = (matches.Home_Score == matches.Away_Score).astype('int')
matches_regular = matches[matches.Stage == 'GROUP_STAGE']
matches_playoff = matches[matches.Stage != 'GROUP_STAGE']

In [44]:
fixtures = pd.read_csv('https://dtai.cs.kuleuven.be/sports/worldcup2026/data/fixtures.csv?v=1')
fixtures['key'] = fixtures.apply(lambda r: tuple(sorted([r['Home Team'], r['Away Team']])),axis=1) #
preds = pd.read_json('https://dtai.cs.kuleuven.be/sports/worldcup2026/data/predictions.json?v=1').reset_index().melt(id_vars='index')
preds[['loss','tie','win','0']] = preds['value'].apply(pd.Series)
preds = preds.drop(columns=['0','value']).dropna().rename(columns={'index':'Home Team','variable':'Away Team'})
fixtures = fixtures.merge(preds,how='left')
fixtures = fixtures.merge(matches.rename(columns={'Home':'Home Team','Away':'Away Team'})[['key','Home_Score','Away_Score',
                                                                                           'Home_Win','Away_Win','Draw']],how='left',on='key') #
fixtures.loc[~fixtures.Home_Score.isna(),'Result'] = 1
fixtures['Home Team'], fixtures['Away Team'] = zip(*fixtures['key'])

In [45]:
fixtures.head(30)

,Round Number,Date,Location,Home Team,Away Team,Group,Result,key,loss,tie,win,Home_Score,Away_Score,Home_Win,Away_Win,Draw
0,1,11/06/2026 15:00,Mexico City,MEX,RSA,Group A,1.0,"(MEX, RSA)",0.108873,0.206114,0.685013,2.0,0.0,1.0,0.0,0.0
1,1,11/06/2026 18:00,Guadalajara,CZE,KOR,Group A,1.0,"(CZE, KOR)",0.266895,0.311116,0.421989,1.0,2.0,0.0,1.0,0.0
2,1,12/06/2026 15:00,Toronto,BIH,CAN,Group B,1.0,"(BIH, CAN)",0.162353,0.259426,0.578222,1.0,1.0,0.0,0.0,1.0
3,1,12/06/2026 18:00,Vancouver,QAT,SUI,Group B,1.0,"(QAT, SUI)",0.781926,0.149081,0.068993,1.0,1.0,0.0,0.0,1.0
4,1,13/06/2026 15:00,Boston,BRA,MAR,Group C,1.0,"(BRA, MAR)",0.244281,0.304530,0.451188,1.0,1.0,0.0,0.0,1.0
5,1,13/06/2026 18:00,Philadelphia,HAI,SCO,Group C,1.0,"(HAI, SCO)",0.623966,0.237947,0.138087,0.0,1.0,0.0,1.0,0.0
6,1,14/06/2026 15:00,Los Angeles,PAR,USA,Group D,1.0,"(PAR, USA)",0.347475,0.319513,0.333012,1.0,4.0,0.0,1.0,0.0
7,1,14/06/2026 18:00,Seattle,AUS,TUR,Group D,1.0,"(AUS, TUR)",0.419428,0.311639,0.268933,2.0,0.0,1.0,0.0,0.0
8,1,15/06/2026 15:00,Houston,CUW,GER,Group E,1.0,"(CUW, GER)",0.025241,0.063545,0.911214,1.0,7.0,0.0,1.0,0.0
9,1,15/06/2026 18:00,Dallas,CIV,ECU,Group E,1.0,"(CIV, ECU)",0.466752,0.300381,0.232868,1.0,0.0,1.0,0.0,0.0
10,1,16/06/2026 15:00,Miami,JPN,NED,Group F,1.0,"(JPN, NED)",0.326045,0.319412,0.354543,2.0,2.0,0.0,0.0,1.0
11,1,16/06/2026 18:00,Atlanta,SWE,TUN,Group F,1.0,"(SWE, TUN)",0.263734,0.310142,0.426124,5.0,1.0,1.0,0.0,0.0
12,1,17/06/2026 15:00,Kansas City,BEL,EGY,Group G,1.0,"(BEL, EGY)",0.195053,0.281895,0.523053,1.0,1.0,0.0,0.0,1.0
13,1,17/06/2026 18:00,San Francisco,IRN,NZL,Group G,1.0,"(IRN, NZL)",0.156842,0.254916,0.588243,2.0,2.0,0.0,0.0,1.0
14,1,18/06/2026 15:00,New York/New Jersey,CPV,ESP,Group H,1.0,"(CPV, ESP)",0.038371,0.092175,0.869454,0.0,0.0,0.0,0.0,1.0
15,1,18/06/2026 18:00,Boston,KSA,URU,Group H,1.0,"(KSA, URU)",0.655648,0.221873,0.122479,1.0,1.0,0.0,0.0,1.0
16,1,19/06/2026 15:00,Dallas,FRA,SEN,Group I,1.0,"(FRA, SEN)",0.219796,0.294601,0.485603,3.0,1.0,1.0,0.0,0.0
17,1,19/06/2026 18:00,Houston,IRQ,NOR,Group I,1.0,"(IRQ, NOR)",0.616171,0.241793,0.142036,1.0,4.0,0.0,1.0,0.0
18,1,20/06/2026 15:00,Los Angeles,ALG,ARG,Group J,1.0,"(ALG, ARG)",0.119038,0.218076,0.662887,0.0,3.0,0.0,1.0,0.0
19,1,20/06/2026 18:00,Seattle,AUT,JOR,Group J,1.0,"(AUT, JOR)",0.191281,0.279582,0.529137,3.0,1.0,1.0,0.0,0.0
20,1,21/06/2026 15:00,Miami,COD,POR,Group K,1.0,"(COD, POR)",0.120031,0.219196,0.660772,1.0,1.0,0.0,0.0,1.0
21,1,21/06/2026 18:00,Atlanta,COL,UZB,Group K,1.0,"(COL, UZB)",0.631497,0.234256,0.134247,3.0,1.0,1.0,0.0,0.0
22,1,22/06/2026 15:00,Toronto,CRO,ENG,Group L,1.0,"(CRO, ENG)",0.200175,0.284833,0.514992,2.0,4.0,0.0,1.0,0.0
23,1,22/06/2026 18:00,Vancouver,GHA,PAN,Group L,1.0,"(GHA, PAN)",0.441554,0.306820,0.251625,1.0,0.0,1.0,0.0,0.0
24,2,18/06/2026 21:00,Mexico City,KOR,MEX,Group A,1.0,"(KOR, MEX)",0.255500,0.308120,0.436379,0.0,1.0,0.0,1.0,0.0
25,2,18/06/2026 21:00,Monterrey,CZE,RSA,Group A,1.0,"(CZE, RSA)",0.505519,0.288107,0.206374,1.0,1.0,0.0,0.0,1.0
26,2,19/06/2026 21:00,Toronto,CAN,QAT,Group B,1.0,"(CAN, QAT)",0.109489,0.206823,0.683688,6.0,0.0,1.0,0.0,0.0
27,2,19/06/2026 21:00,Vancouver,BIH,SUI,Group B,1.0,"(BIH, SUI)",0.694514,0.200820,0.104666,1.0,4.0,0.0,1.0,0.0
28,2,20/06/2026 21:00,Boston,BRA,HAI,Group C,NaN,"(BRA, HAI)",0.043601,0.102816,0.853584,NaN,NaN,0.0,0.0,0.0
29,2,20/06/2026 21:00,Philadelphia,MAR,SCO,Group C,1.0,"(MAR, SCO)",0.189533,0.278571,0.531896,1.0,0.0,1.0,0.0,0.0

In [98]:
paths = pd.read_json('https://dtai.cs.kuleuven.be/sports/worldcup2026/data/data.json?v=1')
odds = []

for i in range(0,len(paths)):
    temp = paths.iloc[i]
    temp_team = temp['name']
    temp_paths = temp.paths
    for j in range(0,len(temp_paths)):
        temp_path = temp_paths[j]
        temp_path_level = len(temp_path['pos_path'])
        temp_path_probability = temp_path['probability']
        if (temp_path_level == 1) & (temp_path['pos_path'][0].endswith('1')):
            odds.append([temp_team,'1st',temp_path_probability])   
        if (temp_path_level == 1) & (temp_path['pos_path'][0].endswith('2')):
            odds.append([temp_team,'2nd',temp_path_probability])   
        if (temp_path_level == 1) & (temp_path['pos_path'][0].endswith('3')):
            odds.append([temp_team,'3rd',temp_path_probability])        
        if (temp_path_level == 1) & (temp_path['pos_path'][0].endswith('4')):
            odds.append([temp_team,'4th',temp_path_probability])
        odds.append([temp_team,temp_path_level,temp_path_probability])
odds = pd.DataFrame(odds,columns=['country','level','odds'])
odds = odds.groupby(['country','level']).agg({'odds':'sum'}).reset_index().pivot(index='country',columns='level',values='odds').fillna(0)
odds_group = odds[['1st','2nd','3rd','4th']]
odds = odds.drop(columns=odds_group.columns)

In [138]:
standings = groups.copy(True)
standings['W'] = 0
standings['D'] = 0
standings['L'] = 0
standings['GF'] = 0
standings['GA'] = 0
standings['GD'] = 0
standings['Proj'] = 0.0
standings['PPR'] = 0
standings['Points'] = 0
standings['PointsbyMatch'] = [[]]*len(standings)

results = fixtures[~fixtures.Result.isna()]
planned = fixtures[fixtures.Result.isna()]
playoffs = planned[planned.Group.isna()]
planned = planned[~planned.Group.isna()]

for match in range(0,len(results)):
    temp = results.iloc[match]
    standings.loc[standings.Short == temp['Home Team'],'W'] = standings.W + temp.Home_Win
    standings.loc[standings.Short == temp['Home Team'],'D'] = standings.D + temp.Draw
    standings.loc[standings.Short == temp['Home Team'],'L'] = standings.L + temp.Away_Win
    standings.loc[standings.Short == temp['Home Team'],'GF'] = standings.GF + temp.Home_Score
    standings.loc[standings.Short == temp['Home Team'],'GA'] = standings.GA + temp.Away_Score
    standings.loc[standings.Short == temp['Home Team'],'PointsbyMatch'] = standings.PointsbyMatch.apply(lambda lst: lst + [temp.Home_Win * 3 + temp.Draw])

    standings.loc[standings.Short == temp['Away Team'],'W'] = standings.W + temp.Away_Win
    standings.loc[standings.Short == temp['Away Team'],'D'] = standings.D + temp.Draw
    standings.loc[standings.Short == temp['Away Team'],'L'] = standings.L + temp.Home_Win
    standings.loc[standings.Short == temp['Away Team'],'GF'] = standings.GF + temp.Away_Score
    standings.loc[standings.Short == temp['Away Team'],'GA'] = standings.GA + temp.Home_Score
    standings.loc[standings.Short == temp['Away Team'],'PointsbyMatch'] = standings.PointsbyMatch.apply(lambda lst: lst + [temp.Away_Win * 3 + temp.Draw])

    standings.loc[(standings.Short != temp['Home Team']) & (standings.Short != temp['Away Team']),'PointsbyMatch'] = standings.PointsbyMatch.apply(lambda lst: lst + [0])
    
for match in range(0,len(planned)):
    temp = planned.iloc[match]
    standings.loc[standings.Short == temp['Home Team'],'Proj'] = standings.Proj + temp.win * 3 + temp.tie
    standings.loc[standings.Short == temp['Away Team'],'Proj'] = standings.Proj + temp.loss * 3 + temp.tie
    standings.loc[standings.Short == temp['Home Team'],'PPR'] = standings.PPR + 3
    standings.loc[standings.Short == temp['Away Team'],'PPR'] = standings.PPR + 3

for team in range(0,len(odds)):
    temp = odds.iloc[team]
    standings.loc[standings.Short == temp.name,'Proj'] = standings.Proj + temp[[3,4,5,6,7]].sum() * 5
    if standings[standings.Short == temp.name].PPR.values[0] > 0:
        standings.loc[standings.Short == temp.name,'PPR'] = standings.PPR + 25
    else:
        standings.loc[standings.Short == temp.name,'PPR'] = standings.PPR + (len(temp[temp > 0]) - len(temp[temp >= 1]) - 1) * 5
        #AJ to check once in knockouts but this should work

standings.GD = standings.GF - standings.GA
standings.Points = standings.W * 3 + standings.D * 1
standings.Proj += standings.Points
standings.PPR += standings.Points
standings = standings.merge(odds_group,how='left',left_on='Short',right_index=True).merge(
    odds.drop(columns=[1]).rename(columns={2:'32',3:'16',4:'QF',5:'SF',6:'Final',7:'Win'}),how='left',left_on='Short',right_index=True).fillna(0)
standings[' '] = ''

In [139]:
selected_standings = selections.merge(standings)
standings.to_feather('data/standings.ftr')
selected_standings.to_feather('data/selected_standings.ftr')

In [110]:
#### BREAK
break

SyntaxError: 'break' outside loop (590435331.py, line 2)

In [140]:
standings = pd.read_feather('data/standings.ftr')
selected_standings = pd.read_feather('data/selected_standings.ftr')

In [113]:
fmt_dict = {'Points': '{:.0f}', 'Max': '{:.0f}', 'Projected': '{:.1f}','Uniqueness':'{:0.2%}','W':'{:.0f}','D':'{:.0f}','L':'{:.0f}',
            'GF':'{:.0f}','GA':'{:.0f}','Points':'{:.0f}','1st':'{:0.2%}','2nd':'{:0.2%}','3rd':'{:0.2%}','4th':'{:0.2%}'}

player_standings = selected_standings.groupby('Person').agg({'Points':'sum','PPR':'sum','Proj':'sum','Uniqueness':'mean'}).sort_values(
    ['Points','Proj'],ascending=False).rename(columns={'PPR':'Max','Proj':'Projected'}).reset_index()

ordered_managers = player_standings['Person'].tolist()
for i, manager in enumerate(ordered_managers):
    player_detail = selected_standings[selected_standings.Person == manager][[' ','Country','Short','Group','Points','PPR','Proj','Uniqueness']].rename(
        columns={'PPR':'Max','Proj':'Projected'})
    player_detail[" "] = player_detail["Short"].apply(lambda x: f"data/flags/{x}.png")
    pts_val = selected_standings[selected_standings.Person == manager].Points.sum()
    proj_val = selected_standings[selected_standings.Person == manager].Proj.sum()
    leader_icon = "🥇 " if i == 0 else "🥈 " if i == 1 else "🥉 " if i == 2 else ""
top_teams = standings.sort_values(['Points','Proj'],ascending=False)[[' ','Country','Group','Points','PPR','Proj','W','D','L','GD']].rename(
        columns={'PPR':'Max','Proj':'Projected'})

player_over_time = selected_standings[['Person', 'PointsbyMatch']]
player_over_time = player_over_time.join(pd.DataFrame(player_over_time['PointsbyMatch'].tolist(),index=player_over_time.index))
player_over_time = player_over_time.groupby('Person').sum(numeric_only=True).cumsum(axis=1)

In [115]:
ordered_groups = groups.Group.unique().tolist()
for i, group in enumerate(ordered_groups):
    team_detail = standings[standings.Group == group][[' ','Country','W','D','L','GF','GA','GD','Points',' ','PPR','Proj','1st','2nd','3rd','4th'
                                                      ]].sort_values(['Points','GD','GF'],ascending=False).rename(
        columns={'PPR':'Max','Proj':'Projected'})

knockout_detail = standings[['Country','PPR','Proj',' ','32','16','QF','SF','Final','Win']]

In [166]:
player_over_time

             0    1    2    3
Person
AJ B       3.0  3.0  5.0  5.0
Anita VR   0.0  0.0  1.0  1.0
Caity H    3.0  3.0  3.0  3.0
Gavin F    0.0  0.0  1.0  1.0
Geoff T    0.0  0.0  0.0  0.0
Ian C      0.0  0.0  2.0  2.0
Jessie DB  0.0  0.0  0.0  0.0
Laura B    0.0  0.0  0.0  0.0
Matt C     0.0  0.0  1.0  1.0
Nick P     0.0  0.0  0.0  0.0
Steph S    0.0  0.0  1.0  1.0
Tim C      0.0  0.0  1.0  1.0
Yasmin S   0.0  0.0  0.0  0.0

In [175]:
selected_standings[['pot','Country','Count','Short']].drop_duplicates()
standings[['Country','Short']]
selections

       Person pot             Country  Count  Uniqueness
0     Steph S   1              France      7    0.500000
1      Nick P   1               Spain      3    0.833333
2       Ian C   1              France      7    0.500000
3    Yasmin S   1           Argentina      2    0.916667
4     Gavin F   1           Argentina      2    0.916667
..        ...  ..                 ...    ...         ...
73    Caity H   6               Ghana      5    0.666667
74    Laura B   6               Ghana      5    0.666667
75  Jessie DB   6             Curaçao      1    1.000000
76       AJ B   6  Bosnia-Herzegovina      5    0.666667
77   Anita VR   6  Bosnia-Herzegovina      5    0.666667

[78 rows x 5 columns]

player_over_time